name: facebook_ui
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.2  

dev_dependencies:
  flutter_test:
    sdk: flutter
  device_preview: ^1.1.0
  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/emojis/angry.svg
    - assets/images/emojis/heart.svg
    - assets/images/emojis/laughing.svg
    - assets/images/emojis/like.svg
    - assets/images/emojis/sad.svg
    - assets/images/emojis/shocked.svg
    - assets/images/publications/ferrari.jpeg
    - assets/images/publications/flutter.jpeg
    - assets/images/users/1.jpg
    - assets/images/users/2.jpg
    - assets/images/users/3.jpg
    - assets/images/users/4.jpg
    - assets/images/users/5.jpg
    - assets/images/users/6.jpg
    - assets/images/users/7.jpg
    - assets/images/users/8.jpg
    - assets/images/wallpapers/1.jpeg
    - assets/images/wallpapers/2.jpeg
    - assets/images/wallpapers/3.jpeg
    - assets/images/wallpapers/4.jpeg
    - assets/images/wallpapers/5.jpeg
    - assets/images/wallpapers/6.jpeg
    - assets/images/logos/facebook.svg


  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/icons/CustomIcons.ttf

  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
